# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
# Default values for openam-install.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value


component: amster


# Server base URL *within* the Kubernetes cluster - not the external LB URL.
# No /openam appended here.
serverBase: http://openam:80

# See the _helpers template to change the *external* load balancer fqdn
# By default it expands to  openam.$namespace.$baseDomain

# Install passwords.
amadminPassword: password
encryptionKey: "123456789012"
policyAgentPassword: Passw0rd


configStore:
  # type can be dirServer or embedded.
  type: dirServer
   # If type is set to embedded, the attributes below are ignored.
  suffix:  "dc=openam,dc=forgerock,dc=org"
  # This is the first StatefulSet name:
  host: configstore-0.configstore
  port: 1389
  dirManager: "cn=Directory Manager"
  adminPort: 4444
  password: password

# This is not currently supported on install by amster. You must import a user store config.
userStore:
  host:  userstore-0.userstore
  port: 1389
  password: password
  dirManager: "cn=Directory Manager"
  suffix: "dc=openam,dc=forgerock,dc=org"


# determines if '--clean true' is used for the import-config.
# suggest this is 'true' if importing a complete configuration
# and set to 'false' if importing partial/incremental configurations
amsterClean: false

# Defines default global values. These can get overridden with -f custom.yaml
global:
  domain: .example.com
  image:
    repository: forgerock
    pullPolicy: IfNotPresent
    tag: 5.5.0
  git:
    # git repo to clone. The value below is a public git repo that does not require authentication.
    repo: "https://stash.forgerock.org/scm/cloud/forgeops-init.git"
    branch: master
    projectDirectory: "/git/forgeops-init"
  configPath:
    am: /git/forgeops-init/default/am/empty-import

amster:
  exportPath: default/openam/autosave
# For production you wil want to set CPU limits to help Kube Schedule the pods.
resources:
 limits:
   memory: 756Mi
 requests:
   memory: 756Mi
