# Copyright (c) 2016-2017 ForgeRock AS.
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "instanceName" . }}
  labels:
    djInstance: {{ template "instanceName" . }}
    app: {{ template "fullname" . }}
    vendor: forgerock
    component: {{ .Values.component }}
spec:
  serviceName: {{ template "instanceName" . }}
  replicas: {{default 1 .Values.replicaCount }}
  {{- if .Values.djPersistence }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ default "5Gi"  .Values.storageSize }}
      {{- if .Values.storageClass }}
      storageClassName:  {{ .Values.storageClass }}
      {{- end }}
  {{- end }}
  template:
    metadata:
      labels:
        djInstance: {{ template "instanceName" . }}
        app: {{ template "fullname" . }}
        vendor: forgerock
        component: opendj
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: git-init
        image: {{ template "gitImage" . }}
        imagePullPolicy:  {{ template "pullPolicy" . }}
        volumeMounts:
        - name: git
          mountPath: /git
        - name: git-secret
          mountPath: /etc/git-secret
        args: ["init"]
        envFrom:
        - configMapRef:
            name: {{ template "instanceName" . }}
      containers:
      - name: opendj
        image:  {{ template "image" . }}
        imagePullPolicy: {{ template "pullPolicy" . }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        envFrom:
        - configMapRef:
            name: {{ template "instanceName" . }}
        ports:
        - containerPort: 1389
          name: ldap
        - containerPort: 4444
          name: djadmin
        volumeMounts:
        - name: dj-secrets
          mountPath: /var/run/secrets/opendj
        - name: dj-backup
          mountPath: /opt/opendj/backup
        - name: git
          mountPath: /git
        {{- if .Values.djPersistence }}
        - name: data
          mountPath: /opt/opendj/data
        {{- end }}
        readinessProbe:
          exec:
            command: ["/opt/opendj/probe.sh"]
          periodSeconds: 20
          initialDelaySeconds: 30
        livenessProbe:
          exec:
            command: ["/opt/opendj/probe.sh"]
          initialDelaySeconds: 300
          periodSeconds: 60
      {{- if .Values.enableGcloudBackups }}
      # An example of enabling backup to google cloud storage.
      # The bucket must exist, and the cluster needs --scopes storage-full when it is created.
      # This runs the gsutil command periodically to rsync the contents of the /backup folder (shared with the DJ container) to cloud storage. 
      - name: backup
        image: gcr.io/cloud-builders/gcloud
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sh", "-c", "while true; do gsutil -m rsync -r /backup {{ .Values.gsBucket }} ; sleep 600;  done"]
        volumeMounts:
        - name: dj-backup
          mountPath: /backup
      {{- end }}
      volumes:
      - name: dj-secrets
        secret:
          secretName: {{ template "instanceName" . }}
      - name: dj-backup
        emptyDir: {}
      - name: git
        emptyDir: {}
      - name: git-secret
        secret:
          secretName: {{ template "instanceName" . }}